### ISSUE TITLE
Daily Rewards have broken

### ISSUE THREAD

**Issue by BearNationSMP** [Pugabyte/BearNation#634] opened 2021-04-28 20:09 UTC
**Lexi**: Several players have not received their daily rewards today for 15 minutes of playtime including me, skoda, and Power

![image](https://cdn.discordapp.com/attachments/158998209140752384/837056993101217832/unknown.png)

**Comment by lexikiq** [comment] 2021-04-29 00:27
it seems a reload has fixed the listed individuals, but the underlying issue is still occurring

![image](https://user-images.githubusercontent.com/13265322/116487667-7fd52780-a85e-11eb-9591-c0c7fb94b5be.png)

**Comment by Pugabyte** [comment] 2021-04-29 01:13
Added failsafe in https://github.com/Pugabyte/Nexus/commit/04819d38f87f253a3bf38306c1a5a4397db3d50e as well as debug for the most likely cause (the task not getting started when the plugin loads): `/dr getLastTaskTime` (should show near current timestamp). Closing, reopen if it happens again.

**Closed by Pugabyte** 2021-04-29 01:13 UTC

**Comment by Pugabyte** [comment] 2021-04-29 20:31
Caused by https://github.com/Pugabyte/Nexus/commit/a9c83e8e384337a59535f70622b5fe49af965650
